api:
  dashboard: true
  insecure: false

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: contato@sindycondo.com.br
      storage: /acme/acme.json
      tlsChallenge: {}

providers:
  docker:
    exposedByDefault: false
