# Generated by Django 5.0.1 on 2026-03-05 21:23

import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Condominio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "cnpj",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("endereco", models.TextField()),
                ("cidade", models.CharField(blank=True, max_length=200, null=True)),
                ("estado", models.CharField(blank=True, max_length=2, null=True)),
                ("cep", models.CharField(blank=True, max_length=20, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("blocos", models.IntegerField(blank=True, default=1, null=True)),
                ("total", models.IntegerField(blank=True, default=1, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Condominio",
                "verbose_name_plural": "Condominios",
                "db_table": "condominio",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("sindico", "Sindico"),
                            ("porteiro", "Porteiro"),
                            ("morador", "Morador"),
                        ],
                        default="morador",
                        max_length=10,
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("apartamento", models.CharField(blank=True, max_length=20, null=True)),
                ("bloco", models.IntegerField(blank=True, null=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("face_embeddings", models.JSONField(blank=True, null=True)),
                ("notificacoes_push", models.BooleanField(default=True)),
                ("notificacoes_whatsapp", models.BooleanField(default=True)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condominio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="gestao.condominio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "ordering": ["nome"],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.CharField(max_length=100)),
                ("tabela", models.CharField(max_length=50)),
                ("registro_id", models.IntegerField(null=True)),
                ("detalhes", models.JSONField(null=True)),
                ("ip_address", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestao.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "db_table": "log_audit",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(blank=True, max_length=20)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="visitantes/"),
                ),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("max_pessoas", models.IntegerField(default=1)),
                ("qr_code_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "qr_code_imagem",
                    models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando aprovação"),
                            ("approved", "Aprovado"),
                            ("blocked", "Bloqueado"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("usos_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "condominio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitantes",
                        to="gestao.condominio",
                    ),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitantes_autorizados",
                        to="gestao.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitante",
                "verbose_name_plural": "Visitantes",
                "db_table": "visitantes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistroAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_acesso",
                    models.CharField(
                        choices=[
                            ("qr", "QR Code"),
                            ("facial", "Reconhecimento Facial"),
                            ("placa", "Placa Veículo"),
                            ("manual", "Liberação Manual"),
                            ("chave", "Chave Digital"),
                        ],
                        max_length=20,
                    ),
                ),
                ("autorizado", models.BooleanField(default=False)),
                ("motivo_negado", models.CharField(blank=True, max_length=200)),
                ("face_confidence", models.FloatField(blank=True, null=True)),
                ("placa_detectada", models.CharField(blank=True, max_length=20)),
                (
                    "imagem_snapshot",
                    models.ImageField(blank=True, null=True, upload_to="acessos/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "condominio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acessos",
                        to="gestao.condominio",
                    ),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acessos",
                        to="gestao.usuario",
                    ),
                ),
                (
                    "porteiro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acessos_liberados",
                        to="gestao.usuario",
                    ),
                ),
                (
                    "visitante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestao.visitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Acesso",
                "verbose_name_plural": "Registros de Acesso",
                "db_table": "registros_acesso",
                "ordering": ["-timestamp"],
            },
        ),
    ]
