# Generated by Django 5.0.1 on 2026-03-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="status_cadastro",
            field=models.CharField(
                choices=[
                    ("pendente", "Aguardando aprovação"),
                    ("aprovado", "Aprovado"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="aprovado",
                max_length=10,
            ),
        ),
    ]
