# Generated by Django 5.0.1 on 2026-03-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0002_add_status_cadastro_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="status_cadastro",
        ),
    ]
