# Generated by Django 5.0.1 on 2026-03-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0003_remove_status_cadastro_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
