# Generated by Django 5.0.1 on 2026-03-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0004_add_cpf_usuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="condominio",
            old_name="total",
            new_name="total_apartamentos",
        ),
        migrations.AddField(
            model_name="condominio",
            name="total_vagas",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
