# Generated by Django 5.0.1 on 2026-03-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0005_rename_total_add_vagas_condominio"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="vaga_garagem",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="apartamento",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
