# Generated by Django 5.0.1 on 2026-03-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0006_add_vaga_garagem_int_apartamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="vaga_garagem",
        ),
        migrations.CreateModel(
            name="Garagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                (
                    "condominio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garagens",
                        to="gestao.condominio",
                    ),
                ),
                (
                    "morador",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="garagem",
                        to="gestao.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Garagem",
                "verbose_name_plural": "Garagens",
                "db_table": "garagens",
                "ordering": ["condominio", "numero"],
                "unique_together": {("condominio", "numero")},
            },
        ),
    ]
