# Generated by Django 5.0.1 on 2026-03-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0007_add_garagem_remove_vaga_garagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garagem",
            name="numero",
            field=models.CharField(max_length=20),
        ),
    ]
