# Generated by Django 5.0.1 on 2026-03-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0008_garagem_numero_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="papel",
            field=models.CharField(
                blank=True,
                choices=[("titular", "Titular"), ("dependente", "Dependente")],
                default="titular",
                max_length=10,
                null=True,
            ),
        ),
    ]
