# Generated by Django 5.0.1 on 2026-03-10 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0009_add_papel_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tipo", "sindico")),
                fields=("condominio",),
                name="unique_sindico_por_condominio",
            ),
        ),
    ]
