# Generated by Django 5.0.1 on 2026-03-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0010_unique_sindico_por_condominio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="bloco",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
