# Generated by Django 5.0.1 on 2026-03-10 16:52

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0011_bloco_char"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="garagem",
            options={
                "ordering": [
                    "condominio",
                    django.db.models.functions.text.Length("numero"),
                    "numero",
                ],
                "verbose_name": "Garagem",
                "verbose_name_plural": "Garagens",
            },
        ),
        migrations.AddField(
            model_name="garagem",
            name="matricula",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="garagem",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("autonoma", "Autônoma"),
                    ("vinculada", "Vinculada"),
                    ("comum", "Comum"),
                ],
                default="vinculada",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="garagem",
            name="morador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="garagens",
                to="gestao.usuario",
            ),
        ),
    ]
